"""
Client = the person receiving support care. Fields map directly to section 3
of the functional requirements doc.

Auth fields below mirror Worker's exactly, since clients get their own login
to the (future) client-facing app, following the same dual-login pattern:
1. `access_code` is unique and generated by the system when an admin creates the
   client - this is Login Option 1, equivalent to a worker's employee_id.
2. `email` is nullable because a client might not link a personal email/password
   (Login Option 2) right away.
3. `is_active` is the field the admin toggles to instantly disable a client's
   login. We never delete a client record outright - deactivating preserves
   their full visit/care history.
4. `must_change_password` starts True and flips to False after the client's
   first forced password reset.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import Column, String, Text, Boolean, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.database import Base


class Client(Base):
    __tablename__ = "clients"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    full_name = Column(String, nullable=False)
    address = Column(String, nullable=False)
    contact_number = Column(String, nullable=False)
    emergency_contact = Column(String, nullable=False)

    care_plan = Column(Text, nullable=True)
    special_instructions = Column(Text, nullable=True)
    risk_assessment = Column(Text, nullable=True)
    medical_notes = Column(Text, nullable=True)

    # Login Option 1: company-issued credentials
    access_code = Column(String, unique=True, nullable=False, index=True)

    # Login Option 2: personal email, linked after account creation
    email = Column(String, unique=True, nullable=True, index=True)

    password_hash = Column(String, nullable=False)
    must_change_password = Column(Boolean, default=True, nullable=False)

    is_active = Column(Boolean, default=True, nullable=False)
    deactivated_at = Column(DateTime(timezone=True), nullable=True)
    deactivation_reason = Column(String, nullable=True)

    # Nullable so deleting the admin who created this client doesn't force
    # deleting the client too - DELETE /admins/{id} nulls this out instead,
    # preserving the record while losing "created by" attribution, same
    # precedent as care_requests.reviewed_by_admin_id.
    created_by_admin_id = Column(UUID(as_uuid=True), ForeignKey("admins.id"), nullable=True)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    terms_acceptances = relationship("ClientTermsAcceptance", back_populates="client")
    shifts = relationship("Shift", back_populates="client")
