"""
Worker = support worker who uses the mobile-first worker app.

Key design decisions worth remembering:
1. `employee_id` is unique and generated by the system when an admin creates the
   worker - this is Login Option 1.
2. `email` is nullable because a worker might not link a personal email/password
   (Login Option 2) right away - they can add it later from their own settings.
3. `is_active` is the field the admin toggles to instantly disable a worker's
   login, per the spec's security requirement. We never delete a worker record
   outright - deactivating preserves their full visit/audit history.
4. `must_change_password` starts True and flips to False after the worker's
   first forced password reset.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import Column, String, Text, Boolean, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.database import Base


class Worker(Base):
    __tablename__ = "workers"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    full_name = Column(String, nullable=False)

    # Login Option 1: company-issued credentials
    employee_id = Column(String, unique=True, nullable=False, index=True)

    # Login Option 2: personal email, linked after account creation
    email = Column(String, unique=True, nullable=True, index=True)

    password_hash = Column(String, nullable=False)
    must_change_password = Column(Boolean, default=True, nullable=False)

    # Self-service profile fields, editable by the worker themselves via
    # PATCH /workers/me - separate from the admin-controlled fields above.
    bio = Column(Text, nullable=True)
    phone_number = Column(String, nullable=True)

    is_active = Column(Boolean, default=True, nullable=False)
    deactivated_at = Column(DateTime(timezone=True), nullable=True)
    deactivation_reason = Column(String, nullable=True)

    # Nullable so deleting the admin who created this worker doesn't force
    # deleting the worker too - DELETE /admins/{id} nulls this out instead,
    # preserving the record while losing "created by" attribution, same
    # precedent as care_requests.reviewed_by_admin_id.
    created_by_admin_id = Column(UUID(as_uuid=True), ForeignKey("admins.id"), nullable=True)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    terms_acceptances = relationship("WorkerTermsAcceptance", back_populates="worker")
    shifts = relationship("Shift", back_populates="worker")
