"""add client authentication

Revision ID: 103574486155
Revises: affb72fb3671
Create Date: 2026-07-17 03:01:25.713562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103574486155'
down_revision = 'affb72fb3671'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_terms_acceptance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('terms_version', sa.String(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Adjusted: the clients table already has rows, and access_code must be both
    # NOT NULL and unique, so a single shared server_default won't work (every
    # existing row would collide on the same value). password_hash is NOT NULL
    # too, and giving every pre-existing client the same dummy hash felt worse
    # than giving each one its own real (if unrecoverable) generated credential,
    # so both columns are added nullable first, backfilled per-row below using
    # the app's own credential-generation logic, then locked down to NOT NULL
    # (+ unique for access_code). must_change_password/is_active are booleans
    # with no uniqueness concern, so those just get a server_default matching
    # their Python-side default.
    op.add_column('clients', sa.Column('access_code', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('email', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('clients', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('deactivation_reason', sa.String(), nullable=True))

    # Backfill existing rows with real, unique, generated credentials. These
    # clients predate the auth system, so nobody knows this password - that's
    # fine for now since there's no client-facing app yet to log into; a future
    # "reset client credentials" admin action is the intended way to onboard them.
    from app.core.security import hash_password
    from app.utils.generators import generate_client_access_code, generate_temporary_password

    connection = op.get_bind()
    existing_codes = set()
    client_rows = connection.execute(sa.text("SELECT id FROM clients")).fetchall()
    for (client_id,) in client_rows:
        access_code = generate_client_access_code()
        while access_code in existing_codes:
            access_code = generate_client_access_code()
        existing_codes.add(access_code)

        password_hash = hash_password(generate_temporary_password())
        connection.execute(
            sa.text("UPDATE clients SET access_code = :access_code, password_hash = :password_hash WHERE id = :id"),
            {"access_code": access_code, "password_hash": password_hash, "id": client_id},
        )

    op.alter_column('clients', 'access_code', nullable=False)
    op.alter_column('clients', 'password_hash', nullable=False)

    op.create_index(op.f('ix_clients_access_code'), 'clients', ['access_code'], unique=True)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_access_code'), table_name='clients')
    op.drop_column('clients', 'deactivation_reason')
    op.drop_column('clients', 'deactivated_at')
    op.drop_column('clients', 'is_active')
    op.drop_column('clients', 'must_change_password')
    op.drop_column('clients', 'password_hash')
    op.drop_column('clients', 'email')
    op.drop_column('clients', 'access_code')
    op.drop_table('client_terms_acceptance')
    # ### end Alembic commands ###
