"""add existing_client_id to care_requests

Revision ID: 2be16f690936
Revises: 52b756caae4e
Create Date: 2026-07-18 04:44:47.848734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be16f690936'
down_revision = '52b756caae4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_requests', sa.Column('existing_client_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'care_requests', 'clients', ['existing_client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'care_requests', type_='foreignkey')
    op.drop_column('care_requests', 'existing_client_id')
    # ### end Alembic commands ###
