"""admin crud, must_change_password, nullable created_by_admin_id

Revision ID: 3eb96134c30a
Revises: 1ba6a3e1ab23
Create Date: 2026-08-12 11:07:59.625888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb96134c30a'
down_revision = '1ba6a3e1ab23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default=false backfills every EXISTING admin row (the account
    # already in use, with a real password already set) as False - they
    # should never be surprised by a forced password change. New admins
    # created afterward get True explicitly from create_admin_with_credentials()
    # (a generated temp password to relay) or False from create_admin.py (they
    # chose their own password) - neither path depends on this server default,
    # so it's dropped right after the backfill rather than left lingering.
    op.add_column(
        'admins',
        sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.alter_column('admins', 'must_change_password', server_default=None)
    op.alter_column('clients', 'created_by_admin_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('shifts', 'created_by_admin_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('workers', 'created_by_admin_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workers', 'created_by_admin_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('shifts', 'created_by_admin_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('clients', 'created_by_admin_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('admins', 'must_change_password')
    # ### end Alembic commands ###
