"""add worker profile fields, ratings, client messaging

Revision ID: 52b756caae4e
Revises: aeb8dcd3f4ee
Create Date: 2026-07-17 20:54:17.321149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b756caae4e'
down_revision = 'aeb8dcd3f4ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_id')
    )
    op.add_column('messages', sa.Column('client_id', sa.UUID(), nullable=True))
    op.alter_column('messages', 'worker_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_messages_client_id'), 'messages', ['client_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'clients', ['client_id'], ['id'])
    op.add_column('workers', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('workers', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'phone_number')
    op.drop_column('workers', 'bio')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_client_id'), table_name='messages')
    op.alter_column('messages', 'worker_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('messages', 'client_id')
    op.drop_table('ratings')
    # ### end Alembic commands ###
