"""add care requests

Revision ID: aeb8dcd3f4ee
Revises: 103574486155
Create Date: 2026-07-17 03:21:04.818509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb8dcd3f4ee'
down_revision = '103574486155'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_name', sa.String(), nullable=False),
    sa.Column('requester_relationship', sa.String(), nullable=False),
    sa.Column('requester_phone', sa.String(), nullable=False),
    sa.Column('requester_email', sa.String(), nullable=False),
    sa.Column('care_recipient_name', sa.String(), nullable=False),
    sa.Column('care_recipient_address', sa.String(), nullable=False),
    sa.Column('care_type_summary', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='carerequeststatus'), nullable=False),
    sa.Column('decline_reason', sa.String(), nullable=True),
    sa.Column('linked_client_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['linked_client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('care_requests')
    # ### end Alembic commands ###
