"""add shift response tracking and broadcast messages

Revision ID: affb72fb3671
Revises: 4cf64c05cb98
Create Date: 2026-07-08 15:14:41.381180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'affb72fb3671'
down_revision = '4cf64c05cb98'
branch_labels = None
depends_on = None

worker_response_enum = postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', name='workerresponsestatus')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted: both tables already have rows, so the new NOT NULL columns need a
    # server_default to backfill existing rows, matching each column's Python-side
    # default (WorkerResponseStatus.PENDING / False). Autogenerate doesn't add this
    # on its own since Python-side `default=` isn't reflected as DDL. Also had to
    # explicitly create the new Postgres enum type first - add_column doesn't do
    # this automatically the way create_table does.
    worker_response_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('messages', sa.Column('is_broadcast', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('shifts', sa.Column('worker_response', worker_response_enum, nullable=False, server_default='PENDING'))
    op.add_column('shifts', sa.Column('decline_reason', sa.Text(), nullable=True))
    op.add_column('shifts', sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'responded_at')
    op.drop_column('shifts', 'decline_reason')
    op.drop_column('shifts', 'worker_response')
    op.drop_column('messages', 'is_broadcast')

    worker_response_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
